// DA-BAN-svelte/src/lib/main/Banner.svelte
<script>
import banner01 from '$assets/main/banner-01.png';
</script>

<div
	class="
		pt-16 ps-8 h-60
		select-none
		bg-[#EDEDED]
		bg-center bg-cover bg-no-repeat
	"
	style="background-image: url({banner01});"
>
	<div class="font-bold text-[1.375rem] leading-[138%]">
		홀리데이<br />
		A Winter Tea Market
	</div>
	<div class="mt-2 text-[0.875rem] leading-[157%]">
		그린티 스카우드 대원들의 <br />
		크리스마스 티 마켓에 초대합니다.
	</div>
</div>

// DA-BAN/components/main/Banner.jsx
// 배너를 동적으로 가져오는 기능이 필요한가?

export const Banner = () => {
	return (
		<div
				className="
				pt-16 ps-8 h-60
				select-none
			bg-[#EDEDED]
				bg-[url('/main/banner-01.png')] bg-center bg-cover bg-no-repeat
				"
		>
			<div className="font-bold text-[1.375rem] leading-[138%]">
				홀리데이<br/>
				A Winter Tea Market
			</div>
			<div className="mt-2 text-[0.875rem] leading-[157%]">
				그린티 스카우드 대원들의 <br/>
				크리스마스 티 마켓에 초대합니다.
			</div>
		</div>
	)
}
